name: myperfectad
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  adaptive_breakpoints: ^0.0.3
  google_fonts: ^1.1.1
  font_awesome_flutter: ^8.10.0
  google_maps_flutter: ^0.5.28
  google_maps_flutter_web: ^0.1.0+8
  flutter_map: any
  url_launcher: ^5.7.10
  provider: ^4.3.2+3
  http: ^0.12.2
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo2.png
    - images/book.png
    - images/cinema.png
    - images/confetti.png
    - images/game-controller.png
    - images/online-shopping.png
    - images/random.png
    - images/toolbox.png
    - images/town.png
    - images/circular-target.png
    - images/arrow-top.png
    - images/arrow-left.png
    - images/girl.png
    - images/boy.png
  # demo images
    - images/demo/demo-1.jpg
    - images/demo/demo-2.jpg
    - images/demo/demo-3.jpg
    - images/demo/demo-4.jpg
    - images/demo/demo-5.jpg
    - images/demo/demo-6.jpg
    - images/demo/demo-7.jpg
    - images/demo/demo-8.jpg
    - images/demo/demo-9.jpg
    - images/demo/demo-10.jpg
    - images/demo/demo-11.jpg
    - images/demo/demo-12.png
    - images/demo/demo-13.jpg
    - images/demo/demo-14.jpg
    - images/demo/demo-15.jpg
    - images/demo/demo-16.jpg
    - images/demo/demo-17.jpg
    - images/demo/demo-18.jpg
    - images/demo/demo-19.jpg
    - images/demo/demo-20.jpg
    - images/demo/demo-21.jpg
    - images/demo/demo-22.jpg
    - images/demo/demo-23.jpg
    - images/demo/demo-24.jpg
    - images/demo/demo-25.jpg
    - images/demo/demo-26.jpg
    - images/demo/demo-27.jpg
    - images/demo/demo-28.jpg
    - images/demo/demo-29.jpg
    - images/demo/demo-30.jpg
    - images/demo/demo-31.jpg
    - images/demo/demo-32.jpg
    - images/demo/demo-33.jpg
    - images/demo/demo-34.jpg
    - images/demo/demo-35.jpg
    - images/demo/demo-36.jpg
    - images/demo/demo-37.jpg
    - images/demo/demo-38.jpg
    - images/demo/demo-39.jpg
    - images/demo/demo-40.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
#    - family: Roboto
#      fonts:
#        - asset: fonts/Roboto-Regular.ttf
#    - family: Montserrat
#      fonts:
#        - asset: fonts/Montserrat-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
    - family: RingBells
      fonts:
        - asset: fonts/RingBells.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
